### ISSUE TITLE
Org Mode Support

### ISSUE THREAD

**Issue by flajann2** [rust-lang/mdBook#1203] opened 2020-04-28 16:43 UTC
Would you be open to pull requests for support for Org Mode? Just curious. Not making any commitment just yet.

**Comment by Dylan-DPC** [comment] 2020-04-28 17:50
@flajann2 sure go ahead

**Comment by ehuss** [comment] 2020-04-28 17:55
I'm not sure what Org Mode would entail.  Isn't it a different format from markdown?  I don't think we'd want to add additional input formats at this time.  Perhaps try implementing an (external) preprocessor first?

Also, this issue is a duplicate of #1183.

**Comment by ehuss** [comment] 2020-05-18 00:58
Closing as a duplicate of #1183.

**Closed by ehuss** 2020-05-18 00:58 UTC
