### ISSUE TITLE
Code block copy button overlaps with code

### ISSUE THREAD

**Issue by camelid** [rust-lang/mdBook#1363] opened 2020-10-23 00:14 UTC
Not sure what the best way to resolve this is, but thought I would open an issue so there can be discussion. This image is from [this page](https://doc.rust-lang.org/nightly/reference/attributes/type_system.html#the-non_exhaustive-attribute) in the Reference:

![image](https://user-images.githubusercontent.com/37223377/96942415-ec273680-1489-11eb-8194-5f5ef1ef5653.png)

**Comment by ehuss** [comment] 2020-10-23 15:32
Thanks, this is a duplicate of #1322.

**Closed by ehuss** 2020-10-23 15:32 UTC
