### ISSUE TITLE
Add the possibility to link to headings of another markdown file inside SUMMARY.md

### ISSUE THREAD

**Issue by Haislich** [rust-lang/mdBook#2436] opened 2024-09-11 17:11 UTC
### Problem

There are times in which inside a chapter there are a lot of concepts, but each concept is small.
Also, since there are a lot of concepts, getting a good TOC would be great.
As far as the [documentation about SUMMARY.md](https://rust-lang.github.io/mdBook/format/summary.html) is concerned each subchapter should be stored in it's markdown specific file.
Inside markdown [linking to specific headers inside a markdown file is allowed](https://roachhd.gitbooks.io/master-markdown/content/syntax/anchors.html), thus having a `chapter_1.md` and a `SUMMARY.md`  should be valid.

`src/chapter_1.md`
```markdown
# Chapter 

bla bla bla

## Chapter 1.1

Again some bla bla, but 1.1
```
`src/SUMMARY.md`
```markdown
# Summary

- [Chapter 1](./chapter_1.md/#chapter-11)
  -[Chapter 1.2](./chapter_1.md/#chapter-12)
```

`mdbook v0.4.40` responds:

```bash
2024-09-11 18:50:20 [ERROR] (mdbook::utils): Error: Unable to create missing chapters
2024-09-11 18:50:20 [ERROR] (mdbook::utils):    Caused By: Unable to create missing file: ~\books\test_book\src\./chapter_1.md/#chapter-11
2024-09-11 18:50:20 [ERROR] (mdbook::utils):    Caused By: The system cannot find the path specified. (os error 3)
```

**Comment by ehuss** [comment] 2024-09-11 18:00
Thanks for the report! Unless I'm mistaken, this looks like a duplicate of #167, so closing in favor of that.  If there is a reason to keep this open separately, let us know!

**Closed by ehuss** 2024-09-11 18:00 UTC
Labels: C-enhancement

**Comment by antofthy** [comment] 2025-07-01 04:24
Closed...   And yet this was one of the best and simplest descriptions of the problem in all the issues I read.

I would prefer to expand this further, and also allow links to 'external html' or out of the mdbook.
Such links (without a '.md' filetype) would be up to the author to ensure it is correct...  Just give a warning and pass through.  Shouldn't be too hard to implement and would make mdbook much more usefull.
