### ISSUE TITLE
Add `tsx` support

### ISSUE THREAD

**Issue by uhasker** [rust-lang/mdBook#2300] opened 2024-01-27 10:22 UTC
### Problem

I am currently writing a book that contains React + TypeScript examples. While `mdBook` does support `jsx` highlighting, it doesn't support `tsx` highlighting.

For example, if I write this codeblock with a `tsx` highlight:

```tsx
import * as React from "react";

type Task = {
  id: string;
  title: string;
};

export default function TaskList() {
  const [tasks, setTasks] = React.useState<Task[]>([]);
  
  // More code here...
}
```

no highlights are shown at all.

Currently I am working around this by using `jsx` blocks, however, this results in the TypeScript types not being highlighted.

I looked through the docs and saw that `mdBook` uses `highlight.js` for highlighting. According to the `highlight.js` docs, `tsx` is supported (see [this](https://github.com/highlightjs/highlight.js/blob/main/SUPPORTED_LANGUAGES.md)), so I am not quite sure what is going here.

**Comment by ehuss** [comment] 2024-01-27 14:17
Thanks for the report! I believe this is a duplicate of #1674, so closing in favor of that.

**Closed by ehuss** 2024-01-27 14:17 UTC
Labels: C-enhancement
