### ISSUE TITLE
When the homepage is in a subdirectory of src, the image cannot be displayed

### ISSUE THREAD

**Issue by Leroy-X** [rust-lang/mdBook#2202] opened 2023-09-23 06:36 UTC
### Problem

To make the files neater, I created a `docs` folder in `src`. as follows:

book-test/
├── book
└── src
........├── SUMMARY.md
........└── docs
.............├── chapter_1.md
.............└── img
....................└── my_image.jpg

The ·my_image.jpg· image in the `img` folder is used in `chapter_1.md`.
When going directly to the home page, the image cannot be displayed, However, when clicking on the chapter directory, the image can be displayed normally.

I found that the image link in the homepage is wrong, I don't know how to solve it, please help.
Thanks!!!

https://github.com/rust-lang/mdBook/assets/13515498/1572eb66-fe34-4622-9241-9450e4af1749

### Version

```text
v0.4.34
```

**Comment by ehuss** [comment] 2023-09-23 12:35
Thanks for the report! I believe this is a duplicate of #2060, so closing in favor of that.

**Closed by ehuss** 2023-09-23 12:35 UTC
Labels: C-bug
