### ISSUE TITLE
Printing formats wrong with navbar open  

### ISSUE THREAD

**Issue by ehayes2000** [rust-lang/mdBook#2234] opened 2023-11-09 18:24 UTC
### Problem

When I am serving an mdbook with `mdbook serve` and I print to pdf the formatting is incorrect and pushes the content off the page to the right if the navbar is open. 

### Steps

1. Generate some dummy content with at least 2 chapters
2. Use `mdbook serve` to view book
3. Ensure that the navbar on the left is toggled on using the hamburger icon
4. Click the print button in the upper right
5. The formatting of the printed page is wrong

### Possible Solution(s)

Easy fix: 
Toggle off the navbar when the user clicks the print button. 

### Version

```text
mdbook v0.4.35
```

**Comment by ehuss** [comment] 2023-11-10 18:41
Thanks for the report! I'm going to close as a duplicate of #1932. I'm guessing you might be using Firefox. If you are using a different browser, can you please post in that other issue which browser you are using?

**Closed by ehuss** 2023-11-10 18:41 UTC
Labels: C-bug
