### ISSUE TITLE
Buttons in code block can overflow content

### ISSUE THREAD

**Issue by vwkd** [rust-lang/mdBook#1680] opened 2021-11-05 20:30 UTC
If the first line in a code block is sufficiently long to span the width of the code block, the buttons on the right overflow the content.

This is particularly noticeable on mobile where the small screen width makes this occur more often.

![F50351AB-42FB-4324-901B-48F2955D7338](https://user-images.githubusercontent.com/33468089/140574078-604f2eb8-1100-4b0a-9aa0-b5f417f7ff82.jpeg)

There should be a better way to offer the buttons without needing to overflow the content.

**Comment by ehuss** [comment] 2021-11-06 17:33
Thanks for the report.  I think this is a duplicate of #1322, so closing in favor of that.

**Closed by ehuss** 2021-11-06 17:33 UTC
