### ISSUE TITLE
YAML Style Meta-Data

### ISSUE THREAD

**Issue by mofosyne** [rust-lang/mdBook#2254] opened 2023-12-01 12:59 UTC
### Question

Just wondering why mdbook lacks YAML Style Meta-Data support which seems to be common in Jekyll, mkdocs, and other static site generator and document generators

Was trying to convert from jekyll to mdbook

e.g. 

```yaml
---
title: Worker Cooperatives
contributors:
  - Aya.elfadil
---

Worker cooperatives are businesses that are entirely owned and governed
by their employees democratically. Employees typically join the
cooperative by paying a membership fee, and each employee receives one
vote. They are most prevalent in startups and small businesses, though
they can exist in organizations with thousands of employees.
```

**Comment by ehuss** [comment] 2023-12-01 14:54
I think the simple answer is that there hasn't been a need for it.

I believe this is essentially the same as #2142, so closing as a duplicate of that.

**Closed as not planned by ehuss** 2023-12-01 14:54 UTC
Labels: C-question
