### ISSUE TITLE
hide pages/links in SUMMARY.md

### ISSUE THREAD

**Issue by 221V** [rust-lang/mdBook#1625] opened 2021-08-15 12:43 UTC
how i can hide (not include, not show) pages/links in SUMMARY.md ?
thanks

**Comment by ehuss** [comment] 2021-08-15 14:10
All pages must be linked in SUMMARY in order to be included.

**Comment by 221V** [comment] 2021-08-15 16:04
what if i need that pages, but want not see them in sidebar?

can we add any tag for hide links from sidebar?

**Comment by ehuss** [comment] 2021-08-15 17:18
That is currently not possible.  There are issues #830 and #702 tracking that kind of request, but for the most part it is intentional.  If you just want to condense the TOC, you can try out the `fold` functionality described at https://rust-lang.github.io/mdBook/format/configuration/renderers.html.

**Comment by 221V** [comment] 2021-08-16 03:58
all links tags stay at page - so fold is not solution for me((

I want to make page more lightweight

**Comment by ehuss** [comment] 2021-08-22 23:01
Unfortunately that is not possible.  I'm going to close this as a duplicate of the two issues linked above.

**Closed by ehuss** 2021-08-22 23:01 UTC
