### ISSUE TITLE
Line numbers on displayed source code

### ISSUE THREAD

**Issue by dolphin54** [rust-lang/mdBook#1852] opened 2022-07-09 16:50 UTC
Hi,

Any chance of adding line numbers to the side of the display when showing code?
Would make it easier to identify/refer to line when talking about it further on.

Regards
Den

**Comment by ehuss** [comment] 2022-07-09 18:57
Thanks for the suggestion! I believe this is a duplicate of #1303, so closing in favor of that.

**Closed by ehuss** 2022-07-09 18:57 UTC
