### ISSUE TITLE
Print version of mdbook has too much whitespace on the left if sidebar is opened

### ISSUE THREAD

**Issue by robinduerhager** [rust-lang/mdBook#2223] opened 2023-10-20 13:48 UTC
### Problem

If the sidebar is opened and you click the print icon, the generated pdf has a lot of whitespace on the left of the content. When the sidebar is closed, the generated pdf uses all available space.

Here is a little gif that should describe the issue more precisely:
![Gif that shows the pdf layouting problem](https://github.com/rust-lang/mdBook/assets/18482238/86f702cf-dcd0-4f24-ba72-1e3563569c95)

### Steps

1. Open the sidebar for navigation
2. Click the print icon in the upper right corner
3. Look at the generated pdf with whitespace problem
4. Close the sidebar
5. Click on the print icon in the upper right corner
6. Look at the generated PDF with all used space

### Possible Solution(s)

I have 2 ideas to solve this problem:
1. Ignore the Sidebar in the print version.
2. Generate a Table of Contents page no matter if the sidebar is opened or not and let the content use all available pdf space.

### Notes
Happens on:
- Firefox 118.0.2
- Chrome 118.0.5993.89
- Edge 118.0.2088.57

OS: Windows 22H2 Build 19045.3570
I couldn't test Safari.

### Version

```text
mdbook v0.4.35
```

**Comment by robinduerhager** [comment] 2023-10-20 13:51
Whoops, i just posted this and then saw that there actually already is an Issue with this exact Problem: #1932 . So it's a duplicate but I'd want to leave it to you which issue you want to keep open :).

**Comment by ehuss** [comment] 2023-10-20 14:23
Thanks, I'll go ahead and close as a duplicate of #1932.

**Closed by ehuss** 2023-10-20 14:23 UTC
Labels: C-bug
