### ISSUE TITLE
When using `mdbook build some_dir`, preprocessor using relative path doesn't work

### ISSUE THREAD

**Issue by Lorak-mmk** [rust-lang/mdBook#2289] opened 2024-01-11 10:15 UTC
### Problem

If I use a preprocessor written in Python, like in documentation example: https://rust-lang.github.io/mdBook/format/configuration/preprocessors.html#provide-your-own-command , it works correctly when I execute `mdbook build` - so the `book.toml` file is in the same directory.
In the project I'm working on, book is in the `docs` subdirectory, so it's usually built with `mdbook build docs`. But when using this custom preprocessor, it doesn't work when invoked like this, because the PWD is still the main directory, instead of `docs` directory.
This is counterintuitive and limits the ability to use preprocessors.

I created a workaround in the project ( https://github.com/scylladb/scylla-rust-driver/pull/910 ):
```
[preprocessor.sphinx]
command = '''bash -c '
if test -f "./docs/sphinx_preprocessor.py"; then
    python ./docs/sphinx_preprocessor.py "$@" 
else 
    python ./sphinx_preprocessor.py "$@"
fi' run_preprocessor
'''
```

but it's ugly and only allows executing from root or `docs` directories.

### Steps

1. Have some book in a directory `foo`.
2. Create a preprocessor called `bar.py` in `foo` directory.
3. Add entry to book.toml:
```toml
[preprocessor.bar]
command = "python bar.py"
```
4. Go to parent of `foo` directory
5. Execute `mdbook build foo`
6. Book is built, but without using preprocessor, as `bar.py` couldn't be found.

### Possible Solution(s)

Before executing preprocessor command change the PWD to the root of the book

### Version

```text
mdbook v0.4.36
```

**Comment by ehuss** [comment] 2024-01-11 14:39
Thanks for the report! I believe this is a duplicate of #1424, so closing in favor of that.

**Closed as not planned by ehuss** 2024-01-11 14:39 UTC
Labels: C-bug
