### ISSUE TITLE
Let multiple headings in one page occupy multiple locations in the left TOC?

### ISSUE THREAD

**Issue by fzyzcjy** [rust-lang/mdBook#1859] opened 2022-07-17 12:09 UTC
Hi I am using this repo for doc of https://fzyzcjy.github.io/flutter_rust_bridge/. It currently looks like:

![image](https://user-images.githubusercontent.com/5236035/179397543-087366ec-68ef-4b43-987c-a220b9acc354.png)

However, I hope, for example, there can be `3.1.3.1 Tuple structs, 3.1.3.2 Non-final fields, ...` etc in the left-hand-side TOC in addition to the `3.1.3 Structs`. In other words, I hope (manually or automatically) one page (one md) can occupy multiple places in TOC.

Is this possible? Thanks!

**Comment by ehuss** [comment] 2022-09-23 00:06
This sounds more or less like a duplicate of #167, so closing in favor of that.

**Closed by ehuss** 2022-09-23 00:06 UTC
