### ISSUE TITLE
Index page of the book can have broken relative links when in a subdirectory

### ISSUE THREAD

**Issue by meator** [rust-lang/mdBook#2341] opened 2024-03-22 17:51 UTC
### Problem

When the first page in `SUMMARY.md` is in a subdirectory, relative links behave differently when entering the page through book's `index.html` and when entering it normally.

### Steps

Sample book can be found here: 
[sample-book.tar.gz](https://github.com/rust-lang/mdBook/files/14726624/sample-book.tar.gz)

When you run

```
mdbook serve
```

and click the `Link to chapter 2`, you will be redirected to 404. If you first click on `Chapter 1` on the left panel, the link will work.

### Version

```text
mdbook v0.4.37
```

**Comment by ehuss** [comment] 2024-04-24 02:35
Thanks for the report! I believe this is a duplicate of #2060, so closing in favor of that.

**Closed by ehuss** 2024-04-24 02:35 UTC
Labels: C-bug
