### ISSUE TITLE
Make Playground URL configurable

### ISSUE THREAD

**Issue by hmn53** [rust-lang/mdBook#2199] opened 2023-09-22 05:38 UTC
### Problem

Hi! Thanks for this great project.

I have been using `mdbook` for quite some time now. As others have mentioned, sometimes the official playground server is down or slow. The projects I have been using with `mdbook` requires to run the code a lot of times, which becomes difficult sometimes due to timeout. 

Also I have seen others mention that they want to run code for languages other than rust as well. 

### Proposed Solution

We can make the playground url inside `book.js` configurable so that the user can point it to some other playground or even to their own server. 

Thanks for your time.

**Comment by ehuss** [comment] 2023-09-22 11:09
Thanks for the report! I believe this is a duplicate of #350, so closing in favor of that.

**Closed by ehuss** 2023-09-22 11:09 UTC
Labels: C-enhancement
