### ISSUE TITLE
Hidden code blocks no longer sent to rust Playground?

### ISSUE THREAD

**Issue by cfsamson** [rust-lang/mdBook#1949] opened 2022-12-12 22:24 UTC
I've had a lot of errors lately when re-building some of my mdbooks on the CI server. On mdbook version 0.4.15 all code snipptes run as expected but the ones with parts of code hidden by `#` seem to fail by not sending the part of the code which is hidden to the playground when using the latest version (0.4.22). If you expand the hidden parts, everything works as expected.

**Comment by ehuss** [comment] 2022-12-13 17:43
This seems to be a regression due to #1911.  @yoyomo can you look at posting a fix?

**Comment by ehuss** [comment] 2022-12-14 14:57
Fixed by #1950.

**Closed by ehuss** 2022-12-14 14:57 UTC
Labels: T-Regression, A-Playground, P-high
