### ISSUE TITLE
Bug: separator gets folded by subsection

### ISSUE THREAD

**Issue by expikr** [rust-lang/mdBook#2362] opened 2024-04-12 20:42 UTC
0.4.37

```toml
# book.toml
output.html.fold.enable = true
```

```md
<!-- SUMMARY.md -->
- [Chapter 1](./chapter_1.md)
- [Chapter 2](./chapter_2.md)
  - [Hidden Section](./hidden-section.md)

---

[Credits](./credits.md)
```

![image](https://github.com/rust-lang/mdBook/assets/77922942/b5bdc363-ae01-4e5a-b6ba-856f1e541a40)

![image](https://github.com/rust-lang/mdBook/assets/77922942/9212bd1b-1417-48cd-9ac6-befda3b6bf53)

**Comment by ehuss** [comment] 2024-04-15 19:57
The spacer is added to the TOC [here](https://github.com/rust-lang/mdBook/blob/c671c2e90486b6ec72921a5043dac1c1c5565f76/src/renderer/html_handlebars/helpers/toc.rs#L77-L81). It's a bit tricky how that interacts with `current_level`. At a glance I'm not sure how that should be better organized.

**Comment by ehuss** [comment] 2024-04-19 14:31
Note, this is a duplicate of #733.

**Closed as completed** 2024-05-17 04:38 UTC
Labels: C-bug, A-Summary
