### ISSUE TITLE
git submodules

### ISSUE THREAD

**Issue by r3k2** [rust-lang/mdBook#1305] opened 2020-08-28 01:55 UTC
Hello, wondering if one can add parts of the src as/from a git submodule, example.
I want to add pieces from another project, or I want to be able to separate pieces on their own repo to be part of a blog post for that particular piece and not the whole book... etc.

Thanks
PS: BTW how do I force one of the current themes to be the default? like Coal one?

**Comment by marco-m-pix4d** [comment] 2020-10-26 09:47
Hello, if I understand correctly, this is a duplicate of #1347.

**Comment by ehuss** [comment] 2021-07-04 15:07
Yea, closing this as a duplicate of #1347.

**Closed by ehuss** 2021-07-04 15:07 UTC
