### ISSUE TITLE
`Table of contents` in right side 🔥

### ISSUE THREAD

**Issue by deependujha** [rust-lang/mdBook#2349] opened 2024-04-04 16:55 UTC
### Problem

- Books generated in the current version don't have a `quick lookup table content`.
- It's a handy feature and very helpful while looking for something.

<img width="1440" alt="Screenshot 2024-04-04 at 10 18 11 PM" src="https://github.com/rust-lang/mdBook/assets/76887609/6996536e-5c4e-49dd-8afa-7b49b5faca4c">

### Proposed Solution

- Something like [FastAPI docs](https://fastapi.tiangolo.com/advanced/path-operation-advanced-configuration/) will be great addition.

<img width="1440" alt="Screenshot 2024-04-04 at 10 13 40 PM" src="https://github.com/rust-lang/mdBook/assets/76887609/6483ac59-7252-4b4c-8d98-c4e42742ded1">

**Comment by ehuss** [comment] 2024-04-04 18:55
Thanks for the suggestion! I believe this is a duplicate of #1523 and #153, so closing in favor of that.

**Closed by ehuss** 2024-04-04 18:55 UTC
Labels: C-enhancement
