### ISSUE TITLE
mdBook .htaccess?

### ISSUE THREAD

**Issue by xzntrc** [rust-lang/mdBook#1794] opened 2022-04-30 05:02 UTC
Is there any way to implement a `.htacces` file that can be used to negate the `.html` proceeding after the URL? I assumed that the 404 was handled by a `.htaccess` file but that seems to be handled through something else (presumably JS). Which leads back to my question; is there a way to remove the `.html`?

**Comment by ehuss** [comment] 2022-06-01 03:24
I don't know if there is a way to rewrite the URLs to remove the `.html` extension. You may need to look into your webserver's configuration if that is possible, but I think mdBook's linkifier will make that difficult.  I believe this is mostly a duplicate of #1563, so closing in favor of that.

**Closed by ehuss** 2022-06-01 03:24 UTC

**Comment by sspaeti** [comment] 2023-10-05 06:20
I had similar questions. I guess we could do something like this in `.htaccess` (Apache):

```
RewriteEngine On

# If the request ends with a /, try to find the corresponding .html file
RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI}.html -f
RewriteRule ^(.*[^/])/$ $1.html [L]
```

This rule works as follows:

1. The `RewriteCond` checks if the `.html` file corresponding to the directory-like URL exists.
2. If it exists, the `RewriteRule` will rewrite the request to the `.html` file.

For example, with this rule:

- Accessing `https://dedp.online/book/appendix/author/` would serve the content of `https://dedp.online/book/appendix/author.html`.
- Accessing `https://dedp.online/book/appendix/feedback/` would serve the content of `https://dedp.online/book/appendix/feedback.html`.

As for performance concerns:

- **Redirect Overhead**: The overhead of such a rewrite is minimal. In most cases, the end user won't notice any delay. Apache's mod_rewrite is highly efficient. When configured properly, the performance impact is negligible for typical websites.
- **Server Load**: While mod_rewrite is efficient, it's important to note that for high-traffic websites, every additional rule can add some server load. 
    
But I'd rather do something like this https://github.com/rust-lang/mdBook/issues/1563, I'm not sure if that would be a long-term solution 🤔.
