### ISSUE TITLE
bug: hyperlink to another section jumps to wrong location on Firefox 57

### ISSUE THREAD

**Issue by anna-liao** [rust-lang/mdBook#499] opened 2017-11-28 17:42 UTC
While adding a new example in rust-cookbook, I noticed that the hyperlink jumps to the wrong location on Firefox 57.

See https://github.com/rust-lang-nursery/rust-cookbook/pull/371#pullrequestreview-79425714

Comment from @budziq 
> I can reproduce it only on Firefox 57 which due to stylo is more prone to incomplete style flashes. What we experience here is firefox pointing to correct page location but then a highlight.js and mdbooks custom js kicks-in to style the code snippets and hide the lines starting with '#'. The links you are mentioning are in places particularly heavy with '#'. Hiding the '#' lines causes the page to get shorter but firefox viewport does not move anymore.

**Comment by Michael-F-Bryan** [comment] 2017-11-29 18:45
Hmm, so if I've understood this correctly the issue is that code snippet hiding changes the size of the page and the browser's viewport doesn't automatically move to reflect that. @budziq or @anna-liao, please correct me if I'm wrong!

What could we do to fix this? It sounds kinda like a browser issue, but at the same time it's caused because we're using javascript to play around with the page. I'm not an expert in JavaScript, but I imagine a hacky workaround would be to add something after code snippet hiding completes so it moves the viewport to where it's meant to be. That's not exactly ideal though :/

**Comment by budziq** [comment] 2017-11-29 20:54
> Hmm, so if I've understood this correctly the issue is that code snippet hiding changes the size of the page and the browser's viewport doesn't automatically move to reflect that.

Thats about right from my observations (but as you know I have zero webdev experience). I'd probably refrain from any hacky hotfixes as it is not super anoying and leave it to someone with webdev knowhow. I've marked it as Help-needed, we might think about advertising somewhere the need for help from webdev people, I mean in general and not only related to this issue.

**Comment by mrec** [comment] 2019-03-04 17:27
Is the amount to which it's "off" constant, or proportional to the number of hidden lines?

This is an old bug so Firefox and/or mdBook may well have changed, but as of 0.2.1 (and without any hidden lines) the issue I'm seeing is that the section header I'm jumping to gets hidden under the `position:sticky` `menu-bar` element, which is effectively floating on top of the content.

**Comment by ehuss** [comment] 2023-05-28 21:21
I'm presently not able to reproduce any of the issues reported here with Firefox 113. If anyone has any reproductions, feel free to post them or open a new issue. Screenshots or screen recordings would be helpful, as well as books that reproduce the issue.

**Closed by ehuss** 2023-05-28 21:21 UTC
Labels: A-Style, A-JavaScript, C-papercut, E-Help-wanted
