### ISSUE TITLE
Themes don't work in Chrome.

### ISSUE THREAD

**Issue by emilio** [rust-lang/mdBook#784] opened 2018-09-08 00:50 UTC
Hey, so I was taking a quick look at https://github.com/rust-lang-nursery/rust-bindgen/issues/1367, and realized that chrome rendered differently than Firefox the bindgen book.

Turns out that the theming stuff is not working in Chrome because chrome doesn't wait for stylesheets to load in order to execute script. You can see an example in:

```html
<!doctype html>
<link rel="stylesheet" href="foo.css" onload="console.log('onload')">
<body>
<script>
  console.log("script");
</script>
```

(with an existing `foo.css` file). `onload` doesn't reliably get logged before `script`. You can see the testcase online in https://crisal.io/tmp/load-sheet.html. For me https://rust-lang-nursery.github.io/mdBook/cli/watch.html renders the code blocks dark on chrome, for example.

The reason why they don't work is because `HTMLLinkElement.disabled`, when called via the WebIDL setter, it doesn't do anything if `HTMLLinkElement.sheet` is null (this bit is compatible across browsers, but for more fun related to `disabled` and such I invite you to https://github.com/whatwg/html/issues/3840 :)).

In any case, this should probably just use the `rel` attribute, using `alternate stylesheet` as the `rel` value for the disabled sheets. I _think_ that should work everywhere.

**Comment by ehuss** [comment] 2023-05-28 18:58
Closing per the comment at https://github.com/rust-lang/mdBook/pull/785#issuecomment-601863542, I can't reproduce this. Please comment, reopen, or open a new issue if there is a way to reprduce this now.

**Closed by ehuss** 2023-05-28 18:58 UTC
Labels: A-Style
