### ISSUE TITLE
[preprocessors] include support for style/script

### ISSUE THREAD

**Issue by yinonov** [rust-lang/mdBook#1689] opened 2021-11-15 18:38 UTC
# Include style/script - feature support
MD interpolation support including other MD files or partials of it `{{#include /path/to/file.md}}`.
will it be possible to also support script and styles
which might not be present in deployment

note that supporting local assets can get a little complex when the assets are not present in deployment. for example there could be built assets or that assets depend on 3rd (node_modules). so if the feature request is applicable, could we consider compiling these assets to the book build?

**Comment by ehuss** [comment] 2021-11-15 22:29
This sounds like a duplicate of #1687 (which was opened a few hours ago) and #1222 if I am understanding you correctly.  You want to have a preprocessor to add additional synthesized `.js` files to the asset output? It currently isn't possible for preprocessors to add new files, which is what #1222 is about.

**Comment by yinonov** [comment] 2021-11-16 04:55
Seem like similar symptoms. It's kind of bundler-like loader.
Is "currently isn't possible" mean there's no way to do that? Or needs triage?

**Comment by auser** [comment] 2021-11-16 12:15
@yinonov and @ehuss I've been poking around the source and I'm trying not to make any big changes to the preprocessors, but I'd like to make the PreprocessorContext mutable, which would in turn make it editable. 

@ehuss does this seem like a way to go?

**Comment by auser** [comment] 2021-11-17 22:45
So turning everything mutable has it's own issues. What do you think about having a preprocessor step that occurs before the preprocessing `run()` that returns the `config` object instead of a new book?

@ehuss

**Comment by ehuss** [comment] 2021-11-20 17:00
I don't think making the config mutable is really the right approach.

A problem with adding CSS and JS is that those are HTML-specific, but the preprocessors are renderer agnostic. 

I could imagine extending the return value of the preprocessor to include additional instructions, like "include these javascript files".  And somehow renderers could receive those instructions and adjust its behavior accordingly.

For things like #1222, I would imagine that extra files could also be included.

I don't know exactly what that structure would look like, or what the evolution would look like, though. For example, files could be passed in JSON, but I don't know if there is a performance concern there, and maybe providing a directory for preprocessors to pass in files would be better?  Also, should things like javascript be specific for the HTML renderer, or should that just be for the HTML renderer only?

**Comment by ehuss** [comment] 2022-06-01 04:03
I'm going to close as a duplicate of the linked issues above.

**Closed by ehuss** 2022-06-01 04:03 UTC
