### ISSUE TITLE
Icons in code blocks may block the code if there's a very long one-line code

### ISSUE THREAD

**Issue by yingmanwumen** [rust-lang/mdBook#1795] opened 2022-05-01 09:52 UTC
As title, if a one-line code is very long, such as:

```sh
docker run --rm -it -v $(pwd)/notes:/notes zerokara:latest /root/.cargo/bin/mdbook build /notes
```

then, the icons at the right side of code block may cover on the code like:
![Screenshot_20220501_175137](https://user-images.githubusercontent.com/58961385/166140847-e1cc6870-bf29-47a3-9e87-01021407e89b.png)

**Comment by ehuss** [comment] 2022-05-01 22:53
Thanks for the report! This is a known issue, closing as a duplicate of #1322.

**Closed by ehuss** 2022-05-01 22:53 UTC
