### ISSUE TITLE
When generating a pdf, automatically generate the directory as a bookmark

### ISSUE THREAD

**Issue by colommar** [rust-lang/mdBook#2320] opened 2024-02-19 04:45 UTC
### Problem

I was able to save it as a pdf when I clicked print, and found that it didn't automatically generate the catalog as a bookmark, which made reading a bit of a hassle

### Proposed Solution

Generate Bookmarks

**Comment by ehuss** [comment] 2024-02-19 14:37
Thanks for the report! I believe this is a duplicate of #1817, so closing in favor of that.

**Closed by ehuss** 2024-02-19 14:37 UTC
Labels: C-enhancement
