### ISSUE TITLE
Markdown file isn't included even though it's linked

### ISSUE THREAD

**Issue by ericonr** [rust-lang/mdBook#1232] opened 2020-05-20 14:12 UTC
In https://github.com/void-linux/void-docs/tree/a226ba55acea02b88c2965adb7193c4733917097, the summary doesn't contain a link to the "Common errors" page. The section contents page https://github.com/void-linux/void-docs/blob/a226ba55acea02b88c2965adb7193c4733917097/src/xbps/troubleshooting/index.md does link to "Common errors". This means that "Common errors" isn't included in the generated book, and the link in the section contents gives me a 404 error.

Is this intended behavior? I can open an issue on `mdbook-linkcheck` about it, instead.

**Comment by ehuss** [comment] 2020-05-20 15:03
Thanks for the report. I think this is a duplicate of #830, so closing in favor of that. 
(And, unfortunately, I don't have an answer for how intentional it is.)

**Closed by ehuss** 2020-05-20 15:03 UTC

**Comment by ericonr** [comment] 2020-05-20 15:22
I think it is, thanks!
