### ISSUE TITLE
README.md not changed to index.html in files other than summary

### ISSUE THREAD

**Issue by nihaals** [rust-lang/mdBook#1253] opened 2020-06-12 17:43 UTC
```
docker run -it --rm rust:slim bash
# cargo install mdbook
# mkdir /app
# cd /app
# mdbook init
...
# printf "[Test](./test/README.md)\n[Test 2](./test.md)" > src/SUMMARY.md
# printf "[Test](./test/README.md)" > src/test.md
# mkdir src/test
# printf "# Test" > src/test/README.md
# mdbook build
# cat book/test.html | grep README.html
<p><a href="./test/README.html">Test</a></p>
# ls book/test
index.html
```

**Comment by ehuss** [comment] 2020-09-22 17:09
I believe this is a duplicate of both #984 and #1268, so closing in favor of those.

**Closed by ehuss** 2020-09-22 17:09 UTC
