### ISSUE TITLE
can't search chinese

### ISSUE THREAD

**Issue by zzc1231** [rust-lang/mdBook#1120] opened 2019-12-19 08:45 UTC
can't search chinese
maybe it's necessary

**Comment by peaceshi** [comment] 2020-02-22 10:11
see https://github.com/weixsong/elasticlunr.js/issues/53
https://github.com/rust-lang/mdBook/issues/1081

**Comment by ehuss** [comment] 2020-04-21 23:18
Closing as duplicate of #1081.

**Closed by ehuss** 2020-04-21 23:18 UTC
