### ISSUE TITLE
Clean build directory before preprocessors run instead of after.

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/mdBook#1235] opened 2020-05-23 15:46 UTC
The change shown below introduced a regression in the https://forge.rust-lang.org where the our precessor can no longer generate HTML redirects that we need to maintain compatibility. (<https://github.com/rust-lang/rust-forge/issues/336>). I would propose to perform the clean step *before* preprocessors are run.

https://github.com/rust-lang/mdBook/blob/6c4c3448e35b527253e0d0cd138a70c078514eb0/src/renderer/html_handlebars/hbs_renderer.rs#L315-L318

**Comment by ehuss** [comment] 2020-05-23 15:58
I think this is a duplicate of #1087.  It was intentionally changed, and there is some discussion there of possible solutions. It would be nice to have someone would make a proposal. I've only skimmed it, but it looks like there's an interesting discussion of allowing preprocessors to add "resources", which I think would also solve #1222.

**Comment by XAMPPRocky** [comment] 2020-05-23 16:20
Well I think it should be reverted until there is a solution, otherwise I'll have to pin or maintain a fork of mdbook.

**Comment by ehuss** [comment] 2020-05-23 19:03
I appreciate that it is frustrating when something breaks, but it has been almost 10 months since the change, it would also cause breakage to revert it. I think a more constructive discussion on #1087 would be more fruitful, and provide solutions for everyone. I suspect it is not too difficult to come up with a design for preprocessors to indicate additional resources they want to include.  I encourage you (or anyone) to work with @Michael-F-Bryan to come up with some solution, I'd be happy to review.

Alternatively, if it is just redirect support, I would be happy to have a first-class solution for that (#430).  I know it has come up many times, and would be very valuable.  I'd by happy to discuss that, as well.

Closing as a duplicate of #1087.

**Closed by ehuss** 2020-05-23 19:03 UTC

**Comment by XAMPPRocky** [comment] 2020-05-23 19:27
> I appreciate that it is frustrating when something breaks, but it has been almost 10 months since the change, it would also cause breakage to revert it.

My problem is not the time scale, it's the fact that this project has no respect for semver, this isn't the first time patch releases have broken forge.

**Comment by Dylan-DPC** [comment] 2020-05-23 19:32
Breaking compatibility accidentally doesn't mean we are not respecting semver

**Comment by XAMPPRocky** [comment] 2020-05-23 19:33
> I think this is a duplicate of #1087. It was intentionally changed

**Comment by Michael-F-Bryan** [comment] 2020-05-24 09:54
@XAMPPRocky, how are you generating the redirects? You mention before/after preprocessors, so it sounds like you've written your own `Preprocessor` to insert redirects?

The intent behind a `Preprocessor` is to modify the `Book` after it has been loaded into memory, and return the modified `Book` so it can be rendered by a particular backend (e.g. the HTML renderer). 

Given that design, *when* a renderer chooses to clear its build directory shouldn't matter, because `Preprocessor`s shouldn't know it exists and the directory is "owned" by the renderer.

---

> Alternatively, if it is just redirect support, I would be happy to have a first-class solution for that (#430). I know it has come up many times, and would be very valuable. I'd by happy to discuss that, as well.

I think the best solution would be to incorporate redirects directly into the HTML renderer (as discussed in #430) instead of having to write your own preprocessor. @XAMPPRocky, is that something you would like us to look into implementing?

I'll be free tomorrow and the day after (recovery from an eye operation) so should have plenty of time to implement HTML redirects as a first-class feature.

**Comment by XAMPPRocky** [comment] 2020-05-24 10:39
I've linked how forge generates redirects in its pre-processor below. I'm not interested in collaborating on a solution, breaking my code has already cost me a good chunk of time and stress dealing with people complaining that forge no longer works.

https://github.com/rust-lang/rust-forge/blob/master/blacksmith/src/lib.rs#L131
