### ISSUE TITLE
Multi language book option

### ISSUE THREAD

**Issue by Azgrom** [rust-lang/mdBook#1521] opened 2021-05-05 14:06 UTC
Accordingly to the mdBook guide:

> - language: The main language of the book, which is used as a language attribute <html lang="en"> for example.

And it is defined at `book.toml`:
```toml
[book]
language = "en"
```

So, I wonder if there is plans to make possible something like:
```toml
[book]
language = ["en", "pt-br"]
```
Such that one could press a button and the book would show its content in the different language/idiom.
Is there any alternative backend that do it? If not, what do you think of this idea?

**Comment by ifsheldon** [comment] 2021-05-19 16:11
Also interested in this feature. Any progress?

**Comment by Azgrom** [comment] 2021-05-19 16:34
> Also interested in this feature. Any progress?

The fastest solution I found is to use [zola](https://github.com/getzola/zola). This interesting static site generator have a template that looks like mdbook pages.

The problem is that zola is by no means a mdbook replacer. You have to consider a lot of web dev aspects, while with mdbook you just focus on the content.

**Comment by ehuss** [comment] 2021-07-06 17:48
I think this is a duplicate of #5, so closing in favor of that.

**Closed by ehuss** 2021-07-06 17:48 UTC
