### ISSUE TITLE
Generating a toc when printing the whole book

### ISSUE THREAD

**Issue by Hoffenbar** [rust-lang/mdBook#1997] opened 2023-01-24 23:21 UTC
### Problem

Printing a big book as pdf leaves the reader with no possibility to navigate through the document, or am I wrong?

### Proposed Solution

Output a toc in the pdf.

**Comment by Hoffenbar** [comment] 2023-01-27 13:52
Furthemore, I noticed that Inrra-page-TOCs generated with `mdbook-toc` don't work in a PDF created with the print button in the upper right corner.

**Comment by ehuss** [comment] 2024-02-19 14:37
Thanks for the report! I believe this is a duplicate of #1817, so closing in favor of that.

**Closed by ehuss** 2024-02-19 14:37 UTC
Labels: C-enhancement, A-Print
