### ISSUE TITLE
Support opening in external editors

### ISSUE THREAD

**Issue by ISSOtm** [rust-lang/mdBook#1547] opened 2021-05-25 10:22 UTC
I am designing a Game Boy assembly programming tutorial, with some snippets that it would be interesting to be able to load & edit in [`rgbds-live`](https://daid.github.io/rgbds-live). The current `editable` infrastructure doesn't work well for this, unless we try spawning a GB emulator each time.

In addition, as well as to allow things like Compiler Explorer, which provide more info than just running the program, I would like to be able to specify custom "external editors" in `book.toml`.

Tentative syntaxes:

- ` ```<lang>,external[=<id>[,<id>... ]]` for arbitrary snippets
- `{{#external [id[,id...]] <path>}}` to use the same syntax as `{{#playground}}`

Needed configuration per editor:

- ID (the TOML table key, obviously)
- Name (for the "Open in <name>" tooltip), could default to the ID
- URL with placeholders (e.g. `{text}` for the URL-encoded code, `{base64}` for Base64, etc.)
- Default spec? ("Default for C language"/"Global default")

**Comment by ehuss** [comment] 2021-07-06 17:05
I'm going to close this as a duplicate of #350, which generally covers the "run on different backends".

**Closed by ehuss** 2021-07-06 17:05 UTC

**Comment by ISSOtm** [comment] 2021-07-06 22:21
I opened a separate issue to bring up support for language other than Rust, not just other back-ends for the same language.
