### ISSUE TITLE
emoji isn't rendered correctly

### ISSUE THREAD

**Issue by uriva** [rust-lang/mdBook#1781] opened 2022-04-07 09:25 UTC
example: https://hyroai.github.io/agenda/

![Screenshot - 2022-04-07T122454 951](https://user-images.githubusercontent.com/2490655/162167238-4a323a4c-2035-4729-9826-3b087633f1ac.png)

should look like this:

👩 hi there
🤖 Would you like to order pizza?
👩 yup
🤖 Alright. Are you vegan?

**Comment by afiqzx** [comment] 2022-04-09 02:41
Your link is broken. Shouldn't it be intro.html instead of intro.htm?

**Comment by schungx** [comment] 2022-04-09 03:30
I believe it is a matter of fonts.

I think `Source Code Pro` has support for that emoji.

**Comment by uriva** [comment] 2022-04-10 15:32
@afiqzx sorry about that, fixed

**Comment by FWYongxing** [comment] 2022-04-11 17:19
@uriva 
If this is a font problem which has been fixed, would you close this issue?

**Comment by uriva** [comment] 2022-04-11 18:54
Doesn't look like it's fixed. I'm not selecting a font anywhere in my configuration.

**Comment by clarkfw** [comment] 2022-04-11 19:33
> I believe it is a matter of fonts.
> 
> I think `Source Code Pro` has support for that emoji.

I reproduced this problem on my notebook. The mdBook uses `Source Code Pro` font to render code. Though `Source Code Pro` supports these emoji, but they're not displayed as @uriva expected.
To fix this problem, you can simply delete contents in the red box as shown below:
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/27894831/162813992-78a61d5d-730f-478f-b610-67eb66464e8f.png">
If you don't have a `general.css` file, run `mdbook init --theme` in a temp directory to generate one.

**Comment by clarkfw** [comment] 2022-11-03 19:23
> > I believe it is a matter of fonts.
> > I think `Source Code Pro` has support for that emoji.
> 
> I reproduced this problem on my notebook. The mdBook uses `Source Code Pro` font to render code snippet by default. Though `Source Code Pro` supports these emojis, they're not displayed as @uriva expect. To fix this problem, you can delete contents in the red box as shown below: <img alt="image" width="1587" src="https://user-images.githubusercontent.com/27894831/162813992-78a61d5d-730f-478f-b610-67eb66464e8f.png"> If you don't have a `general.css` file, run `mdbook init --theme` in a temp directory to generate one.

@uriva If this solved the problem, would you mind closing the issue?

**Comment by uriva** [comment] 2022-11-03 19:47
Not sure if it's fixed, you're welcome to check/close.

**Comment by Dylan-DPC** [comment] 2022-11-04 06:22
This looks like a font issue so I am closing this.

**Closed by Dylan-DPC** 2022-11-04 06:22 UTC
Labels: A-fonts
