### ISSUE TITLE
Creating a Page without it being on the Summary 

### ISSUE THREAD

**Issue by Edgehere** [rust-lang/mdBook#1805] opened 2022-05-15 19:07 UTC
I want to create a link on `struct.md` where it will take the user to `example_test_case.md`. `struct` and  `example_test_case.md` are markdown files allocated in the src directory. I use the syntax `[Test Cases](./Test%20Cases/example_text_case.md)` on `struct.md` to achieve this. However it does not work how can I achieve this? 

Contents of `struct.md`:
```
[Test Cases](./Test%20Cases/example_text_case.md)
```

Directory Tree:
```
src:.
└───Test Cases
    └───example_test_case.md
├───struct.md
```

**Comment by ehuss** [comment] 2022-05-15 19:29
Currently pages must be included in `SUMMARY.md`.  I believe this is a duplicate of #702 and #830, so closing in favor of those.

**Closed by ehuss** 2022-05-15 19:29 UTC
