### ISSUE TITLE
[FEATURE REQUEST] Folder option for SUMMARY.md

### ISSUE THREAD

**Issue by VaZark** [rust-lang/mdBook#1538] opened 2021-05-17 21:41 UTC
Is there a standard way to create a Chapter without content or an associated page? Draft chapters assume that the content is not added yet and show a disabled/greyed out text on the sidebar.

What this issue is seeking to address is that while Chapters support a foldable structure but there is no way to use it exclusively as a folder object. 

Is it possible to extend the current parser to extract a non-hyperlinked list element as a folder that doesn't have an index and used solely for organisation in the sidebar and the slug? Or conversely, allow Part Title to be a foldable object?

Ex: https://vazark.gitlab.io/til/python/basics/Cheatsheet.html

**Comment by joshrotenberg** [comment] 2021-06-04 17:31
Just thinking out loud here, I've only briefly looked at the summary parsing code, but I wonder if this would be possible by making a non-link chapter, so something like this (using the mdbook guide `SUMMARY.md` as an example):

Currently, the `Format` section has a top level that is just an index to the subsections:

<img width="1137" alt="Screen Shot 2021-06-04 at 10 19 02 AM" src="https://user-images.githubusercontent.com/3231/120839958-76ef0a00-c51e-11eb-926d-603b7fdd6441.png">

And the markdown in the `SUMMARY.md`:

```markdown
...
- [Format](format/README.md)
    - [SUMMARY.md](format/summary.md)
        - [Draft chapter]()
...
```

Maybe the parser could support the following format in addition:

```markdown
- Format
    - [SUMMARY.md](format/summary.md)
        - [Draft chapter]()
```

Here is the the parsed structure for the `Format` section currently:

```rust
            Link {
                name: "Format",
                location: Some(
                    "format/README.md",
                ),
                number: Some(
                    SectionNumber(
                        [
                            3,
                        ],
                    ),
                ),
```

So in theory,  `location: None` could indicate this is an unlinked header. 🤷 

What this means downstream for renderers is another question, though.

**Comment by ehuss** [comment] 2021-07-06 17:13
Thanks for the suggestion!  I think this is a duplicate of #483, so closing in favor of that.

**Closed by ehuss** 2021-07-06 17:13 UTC
