### ISSUE TITLE
Some books bundled with Rust installation occasionally reset theme when using Pale Moon browser

### ISSUE THREAD

**Issue by quixoticaxis** [rust-lang/mdBook#1750] opened 2022-02-19 17:09 UTC
I originally created [an issue in cargo repository](https://github.com/rust-lang/cargo/issues/10400), but I was advised to open an issue here.

The reproduction steps:

1. Install Pale Moon browser.
2. Download rustup.
3. Install the default toolchain (maybe it can be skipped).
4. Use rustup docs --cargo to open the book in the browser.
5. Navigate to 1.1.
6. Switch the theme to "Rust".
7. Navigate to other partition, for example, to 4.2.7. — the theme resets to the default one.
8. Navigate back to the original partition — the theme is back to "Rust".

I also tried the latest Microsoft Edge and Firefox, and got the following results:
Edge works fine for both online and offline books.
Pale Moon works with online version of the books, but resets the theme when first navigating to another partition in _Cargo book_, _Unstable book_, _Edition guide_, _Rustc book_, and _Embedded book_ (the other offline versions do fine).
The latest Firefox works with online versions of the books, but resets the theme in any of the offline variants.

**Comment by weihanglo** [comment] 2022-02-20 01:59
Thanks for the report. I think I finally got your point.

The problem here is "offline book fails to preserve theme selection". The root cause is that the behavior with `file` protocol in localstorage is undefined, so it might vary from browser to browser. [From MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage):

> In all current browsers, localStorage seems to return a different object for each `file:` URL. In other words, each `file:` URL seems to have its own unique local-storage area. But there are no guarantees about that behavior, so you shouldn't rely on it because, as mentioned above, the requirements for `file:` URLs remains undefined. So it's possible that browsers may change their `file:` URL handling for localStorage at any time. In fact some browsers have changed their handling for it over time.

It feels like Chrome stores all localstorage items under `file://` origin, while Firefox stores localstorage items for each `file:` URL separately.

**Chrome 98**

<img width="300" alt="chrome" src="https://user-images.githubusercontent.com/14314532/154825311-99476190-52fa-4a1d-bdd3-f5941f7129d7.png">

**Firefox 99**

<img width="300" alt="firefox" src="https://user-images.githubusercontent.com/14314532/154825344-1624b268-3361-4cfd-904d-da655919f05d.png">

It's a browser behavior so mdBook gets no way to change it. I current cannot think of any alternative solution either.

**Comment by quixoticaxis** [comment] 2022-02-20 08:58
@weihanglo, I'm much more interested why some books save the theme, while others don't.

I don't know javascript, so maybe I'm doing something wrong, but I modified book.js for both _Rust book_ and _Cargo book_ to include logging.
```javascript
function get_theme() {
        var theme;
        try { theme = localStorage.getItem('mdbook-theme'); } catch (e) { console.log(e); }
        if (theme === null || theme === undefined) {
            console.log("Falling back to the default theme.");
            return default_theme;
        } else {
            console.log("Setting the previously stored theme.");
            return theme;
        }
    }
```
In _Rust book_ I change the theme once and then it works for any partition, so I get `"Falling back to the default theme."` once and then `"Setting the previously stored theme."` while navigating other pages.
In _Cargo book_ I get `"Falling back to the default theme."` for each page.

**Comment by quixoticaxis** [comment] 2022-02-20 09:59
The only difference I can see is that the books that work fine all have the flat directory structure, while the ones that don't preserve the theme have content in nested folders.

**Comment by weihanglo** [comment] 2022-02-20 12:19
@quixoticaxis cool! You find something interesting!

As I mentioned earlier, it seems that the behavior depends on each browser’s implementation. There is no much room for mdBook to help. If you want to delve into it, I believe the hidden gem is inside the source code of Palm Moon.

**Comment by quixoticaxis** [comment] 2022-02-20 13:13
@weihanglo , I guess so, but I feel neither competent nor interested enough, given I've already read through HTML5 spec while I don't even ever do web front-end 😁

Should I close this issue?

**Comment by weihanglo** [comment] 2022-02-20 13:39
I am not a maintainer of mdBook, though I feel like we should close it to reduce the noise of their maintenance work. 🤔

**Closed** 2022-02-20 13:47 UTC

**Comment by antaz** [comment] 2023-07-13 22:14
Hi @quixoticaxis, this issue is still relevant and i think using cookies to set the theme instead of localStorage may resolve this. 
I can work on this if it's possible.

**Comment by quixoticaxis** [comment] 2023-07-13 23:37
@antaz I cannot comment on this, I am not a maintainer, and, well, simply announced my findings.
