### ISSUE TITLE
Option to suppress `.html` in links?

### ISSUE THREAD

**Issue by cyann** [rust-lang/mdBook#2346] opened 2024-03-28 20:36 UTC
### Question

Is there an option to render the links without the `.html` suffix?

I've setup Apache with this:
```apacheconf
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\.html -f
RewriteRule ^(.*)$ $1.html [L,R=301]
```

When a request is made to the server for a URL without a .html extension, this configuration first checks if such a request does not point to a directory and if appending .html to it points to an actual file. If both conditions are met, it then redirects the request to the same URL with the .html extension removed, using a 301 redirect to indicate that the change is permanent. This helps in creating cleaner URLs for users and search engines, potentially improving SEO and user experience

### Version

```text
mdbook v0.4.37
```

**Comment by ehuss** [comment] 2024-03-28 22:02
There currently isn't an option. I believe this is a duplicate of #1563 if I am not mistaken?

**Comment by cyann** [comment] 2024-03-29 19:35
Yes, that's a duplicate, sorry I couldn't find it first.

Would you be interested by a PR?

**Comment by ehuss** [comment] 2024-04-01 20:02
I would love to help, but honestly I probably don't have time to review this feature at this time. I'm a little concerned about the blast radius of a change like that, since links are pretty deeply ingrained in mdbook and have the potential to have a large effect. Perhaps after 0.5 is done, we could be more open for other changes.

I'm going to close as a duplicate of #1563, thanks!

**Closed by ehuss** 2024-04-01 20:02 UTC
Labels: C-question

**Comment by cyann** [comment] 2024-04-12 20:16
Quick and dirty workaround to remove .html extension from all links:
```shell
find book -type f -name '*.html' -exec sed -i '' -e 's|href="\([^"]*\)\.html"|href="\1"|g' {} \;
find book -type f -name '*.html' -exec sed -i '' -e 's|\.html#|#|g' {} \;
sed -i '' -e 's|\.html||g' book/searchindex.js*
```
