### ISSUE TITLE
Exit code 0 with build errors

### ISSUE THREAD

**Issue by jorgecarleitao** [rust-lang/mdBook#1890] opened 2022-09-12 04:46 UTC
The command `mdbook build` returns exit code 0 when there are errors. This hides failed builds in CI builds (among others).

Could it make sense to exit non-zero on builds with errors, so that e.g. `- run: mdbook build` on CI fails?

**Comment by ehuss** [comment] 2022-09-12 04:51
Can you share the output of the error message? `mdbook build` should usually return a nonzero exit code.

**Comment by jorgecarleitao** [comment] 2022-09-12 04:54
Thanks! This build: https://github.com/jorgecarleitao/arrow2/runs/8298204019?check_suite_focus=true (called with `- run: mdbook build guide` on latest mdbook: https://github.com/jorgecarleitao/arrow2/blob/docs/.github/workflows/docs.yml

**Comment by jorgecarleitao** [comment] 2022-09-12 05:01
It seems that it silences errors from Rust snippets?

**Comment by ehuss** [comment] 2022-09-22 23:48
Ah, I see.  I believe this is a duplicate of #1094, so closing in favor of that.

**Closed by ehuss** 2022-09-22 23:48 UTC
