### ISSUE TITLE
markdown automatic hyperlinks 

### ISSUE THREAD

**Issue by ananthp** [rust-lang/mdBook#1455] opened 2021-01-26 07:02 UTC
mdBook creates links when markdown is in this format:

```
For more info see [this](https://example.com)
```

However, it doesn't create links for urls directly inlined in text without additional syntax:

```
For more info see https://example.com
```

These also should be parsed and rendered as links in generated html

**Comment by Joeyh021** [comment] 2021-04-08 16:35
This isnt an issue, the syntax for this uses angular brackets

**Comment by ehuss** [comment] 2021-07-27 01:13
Closing as a duplicate of #1114.

**Closed by ehuss** 2021-07-27 01:13 UTC
