### ISSUE TITLE
real ToC implementation and folder structures

### ISSUE THREAD

**Issue by finzzz** [rust-lang/mdBook#1398] opened 2020-12-12 02:36 UTC
Hello, thanks for making this app. I have been looking for gitbook alternative for a while. Apparently, I am using vscode to view and edit md files. In vscode, I can see folder pane and outline pane. The folder pane is to categorize the content, while the outline pane shows ToC based on md header. I think this is more dynamic structures because I don't need to edit summary.md as in your app. 

Looking forward for v1.

**Comment by ehuss** [comment] 2021-09-08 05:34
I'm not sure I fully understand, but it sounds like this is asking for something like #1016, so I'm going to close as a duplicate of that.

**Closed by ehuss** 2021-09-08 05:34 UTC
