### ISSUE TITLE
Support different URL formats

### ISSUE THREAD

**Issue by srid** [rust-lang/mdBook#2424] opened 2024-08-07 16:38 UTC
### Problem

Presently, mdBook is hardcoded to convert `foo/bar.md` to `foo/bar.html`, with all links to it unconditionally be `foo/bar.html`. This is even the case for `foo/index.html` URL (where the `index.html` part is not necessary; see #1251). 

### Proposed Solution

In addition to the current behaviour, allow a way to configure in `book.toml` different URL formats. Specifically, support these two:

1. **Directory URLs**: Have `foo/bar.md` generate `foo/bar/index.html` instead, and use `foo/bar/` as the URL link to it.
2. **Slug URLs**: Have `foo/bar.md` generate `foo/bar.html`, as usual, _but_ link to it as `foo/bar` - i.e., without the `.html suffix`.
    - This is especially useful to have "pretty URLs" on Github Pages static sites. Instead of `https://rust-lang.github.io/mdBook/cli/serve.html`, users would see `https://rust-lang.github.io/mdBook/cli/serve`

**Comment by ehuss** [comment] 2024-08-11 12:49
Thanks for the suggestion! I believe this is mostly a duplicate of #1563, so closing in favor of that.

**Closed by ehuss** 2024-08-11 12:49 UTC
Labels: C-enhancement
