### ISSUE TITLE
Add optional page-break

### ISSUE THREAD

**Issue by intptr-t** [rust-lang/mdBook#1570] opened 2021-06-07 04:54 UTC
Since version 0.4.8, when I have to include a long word that does not fit on a single line (specifically, a hyperlink, etc.), the h1 header of the next page is out of position in the forced page break.
(https://github.com/rust-lang/mdBook/pull/1485)

I was working on manually adding page breaks (`<div style="page-break-before:always"></div>`) to some sentences.
In pdfs printed from print.html with the current version, I'm suffering from a case where the h1 header comes at the end.

Is it possible to manually opt-out the page break option?

========
## For example, I printed the following book using Google Chrome

```
.
├── book
├── book.toml
└── src
    ├── SUMMARY.md
    ├── chapter_1.md
    └── chapter_2.md
```

**book.toml**
```
[book]
authors = ["UserName"]
language = "en"
multilingual = false
src = "src"
```

**chapter_1.md**
```
# Chapter 1

<https://www.google.com/search?q=mdbook&rlz=1C5CHFA_enJP895JP903&oq=mdbook&aqs=chrome..69i57j69i59j69i60l3.795j0j1&sourceid=chrome&ie=UTF-8>
```

**chapter_2.md**
```
# Chapter 2
Content2
```

**SUMMARY.md**
```
# Summary

- [Chapter 1](./chapter_1.md)
- [Chapter 2](./chapter_2.md)
```

**Preview**

![image](https://user-images.githubusercontent.com/9898058/120960157-37caee00-c796-11eb-943e-d0442df979d1.png)

## Environment
```
% mdbook --version
mdbook v0.4.8

% sw_vers  
ProductName:    Mac OS X
ProductVersion: 10.15.7
BuildVersion:   19H1217

% /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 91.0.4472.77 
```

**Comment by ehuss** [comment] 2021-07-06 16:31
Thanks for the report!  Sorry that was causing you trouble.  I think this is a duplicate of #1190, so I'm going to close in favor of that. If I misunderstood, feel free to reopen.  There are instructions there on how to add the option.

**Closed by ehuss** 2021-07-06 16:31 UTC
