### ISSUE TITLE
Support include directives in SUMMARY.md

### ISSUE THREAD

**Issue by jplwill** [rust-lang/mdBook#2429] opened 2024-08-22 21:03 UTC
### Problem

I have a tool that generates content for inclusion in an mdBook book; but not an entire mdBook.  As a result, when I generate new content I have to update the SUMMARY.md file by hand.

### Proposed Solution

The SUMMARY.md file should support the same `{{#include file.md}}` syntax as other markdown files do.  Then a tool can generate a piece of a SUMMARY.md corresponding to the generated documentation content, and have it included in SUMMARY.md by `mdbook build`, using a mechanism that's already familiar to mdBook content creators.

**Comment by ehuss** [comment] 2024-08-22 21:57
Thanks for the report! Closing as a duplicate of #2287.

**Closed by ehuss** 2024-08-22 21:57 UTC
Labels: C-enhancement
