### ISSUE TITLE
Execute JS code blocks

### ISSUE THREAD

**Issue by XinranSix** [rust-lang/mdBook#2439] opened 2024-09-21 06:03 UTC
### Problem

when where's a js block like js:

```js
console.log("Hello World!")
```

I like it to execute directly, just like the Rust code below:

```rust
fn main () {
    println!("Hello World!");
}
```

**Comment by ehuss** [comment] 2024-09-21 12:17
Thanks for the report! I believe this is a duplicate of #1453 and #350, so closing in favor of those.

**Closed by ehuss** 2024-09-21 12:17 UTC
Labels: C-enhancement
