### ISSUE TITLE
Index.html image references might not be correct

### ISSUE THREAD

**Issue by brandonpille** [rust-lang/mdBook#2171] opened 2023-08-21 12:19 UTC
### Problem

I noticed that the index.html is a copy of the first page in the summary.md. But whenever the first page in the summary.md is in a separate folder and that it contains image references to images in a subdirectory in that folder the images are not found (only on index.html). When I inspect the image source in html I notice that it is not properly pointing to the subdirectory of chapter 1.

Here is the directory structure:
- src/
     - chapter1/
         - img/
             - myimage.jpg 
         - intro.md
     - summary.md

with summary.md:
```
## Some text

- [Intro](chapter1/intro.md)
``` 

### Steps

Recreate the structure defined in problem

### Version

```text
v0.4.34
```

**Comment by ehuss** [comment] 2023-08-21 13:43
Thanks for the report! I believe this is a duplicate of #2060, so closing in favor of that.

**Closed by ehuss** 2023-08-21 13:43 UTC
Labels: C-bug
