### ISSUE TITLE
Is it possible to specify relative paths outside of the book directory ? 

### ISSUE THREAD

**Issue by avhz** [rust-lang/mdBook#2336] opened 2024-03-14 12:18 UTC
### Question

I am wondering if I can put links to outside of the book directory? 

Such as:

```
.
├── my_book
│   ├── book
│   │   ├── ...
│   └── src
│       ├── ...
│   └── SUMMARY.md
├── examples
│   └── example.rs
```

Can I make a link from `SUMMARY.md` to `../../examples/example.rs` outside of the `my_book` directory ?

I tried but get a 404 error. 

### Version

```text
v0.4.37
```

**Comment by ehuss** [comment] 2024-03-14 13:01
I don't think that is supported. You can try using symlinks in the src directory to files outside. I believe this is a duplicate of #1095 (and possibly others like #1095), so closing in favor of those.

**Closed by ehuss** 2024-03-14 13:01 UTC
Labels: C-question
