### ISSUE TITLE
Search in RU or other language

### ISSUE THREAD

**Issue by Albus** [rust-lang/mdBook#1479] opened 2021-02-28 21:51 UTC
!!! __I don't understand javascript__
# I'm trying to turn on the search in `ru` lang.

Added to book.toml
```toml
additional-js = ["theme/lunr.stemmer.support.js","theme/lunr.ru.js"]
```
But the search doesn't work.
Please give me a working example.
The instructions do not give an understanding.

## please help

**Comment by ehuss** [comment] 2021-07-27 01:02
Sorry, I'm not familiar with how to configure or extend elasticlunr to support other languages.  I'm going to close this as a duplicate of #1081.

**Closed by ehuss** 2021-07-27 01:02 UTC
