### ISSUE TITLE
Summary can't deal with fragments, `#id` style deep links

### ISSUE THREAD

**Issue by ctron** [rust-lang/mdBook#2365] opened 2024-04-19 08:42 UTC
### Problem

Having a summary with the following content won't work:

```markdown
* [Foo](foo.md)
  * [Bar](foo.md#bar)
  * [Baz](foo.md#baz)
```

I creates files `foo.md` as well as `foo.md#bar` and `foo.md#baz` in the filesystem. It always links to `foo.md`.

### Steps

1. Use code from above
2. Build
3. use

### Possible Solution(s)

It's a bug, I think it should be fixed. The fragment should be truncated from the file name, it should be keeps when rendering links.

### Version

```text
mdbook v0.4.37
```
```

**Comment by ehuss** [comment] 2024-04-19 14:31
Thanks for the report! I believe this is a duplicate of #167, so closing in favor of that.

**Closed by ehuss** 2024-04-19 14:31 UTC
Labels: C-bug
