### ISSUE TITLE
Some underscores replaced with `<em>` in equation blocks

### ISSUE THREAD

**Issue by alexdewar** [rust-lang/mdBook#2469] opened 2024-11-06 11:18 UTC
### Problem

I'm trying to render the following equation using mdbook's MathJax support:

```txt
$$ q_{r,a,c,ts} \leq process.commodity.constraint.value(up)_{r,a,c,ts} * \left( \sum_{flexible\ c} q_{r,a,c,ts} \right) $$
```

Which should look like this:

![Image](https://github.com/user-attachments/assets/dd815c57-d766-4e56-b84b-9e715b9432f2)

Unfortunately, with `mdbook` it doesn't render at all and I'm just left with the raw text.

### Steps

1. Make a new markdown document containing the above equation
2. Build it with mdbook
3. View the result in your browser

### Possible Solution(s)

Looking at the HTML output reveals:

```html
<p>$$ q_{r,a,c,ts} \leq process.commodity.constraint.value(up)<em>{r,a,c,ts} * \left( \sum</em>{flexible\ c} q_{r,a,c,ts} \right) $$</p>
```

Notice the random `<em>` block in the middle of the equation. Presumably mdbook shouldn't be inserting any HTML into equation blocks, but in any case it's definitely wrong here.

### Version

v0.4.40

**Comment by ehuss** [comment] 2024-11-06 11:30
Thanks for the report! I believe you need to escape underscores with a backslash so they are not interpreted as emphasis. I think this is a duplicate of #662, so closing in favor of that. You may also want to check out [mdbook-katex](https://github.com/lzanini/mdbook-katex) which has better math support.

**Closed by ehuss** 2024-11-06 11:30 UTC
Labels: C-bug

**Comment by alexdewar** [comment] 2024-11-06 12:26
Ahhh I see. That did the trick. Thanks for your speedy response!
