### ISSUE TITLE
Images with relative path not displayed on index.html

### ISSUE THREAD

**Issue by J3rome** [rust-lang/mdBook#2380] opened 2024-05-15 22:31 UTC
### Problem

Given the following folder structure :
```
- SUMMARY.md
- img/
  - image.png
- folderA
  - pageA.md
- folderB
  - pageB.md
```
The first entry in the `SUMMARY.md` point to `[pageA](folderA/pageA.md)`

I added `image.png` in `pageA.md` using a relative path like so :
```
![text](../img/image.png)
```

Once compiled, the images display properly when I navigate to `/folderA/pageA.html` (Which is where I am redirected when clicking on the section in the sidebar).

However, the images are not displayed on `index.html` which is pretty much a copy of `/folderA/pageA.hml`. The link to the image is still `../img/image.png`. I would have expected the image link to be modified to `img/image.png` when the `index.html` was generated since it's one folder up in the hierarchy.

Am I doing something wrong ?

### Notes

I also tested adding a link to another page using the following syntax 
```
[link](../folderB/pageB.md)
```
The same behavior happen where the link on the `index.html` are not rewritten and are therefore broken.

### Version

```text
mdbook v0.4.37
```

**Comment by ehuss** [comment] 2024-05-16 13:59
Thanks for the report! I believe this is a duplicate of #2060, so closing in favor of that.

**Closed by ehuss** 2024-05-16 13:59 UTC
Labels: C-bug
