### ISSUE TITLE
Hope to support the [toc] or [TOC] syntax in Markdown files

### ISSUE THREAD

**Issue by 1506085843** [rust-lang/mdBook#2099] opened 2023-06-15 05:44 UTC
### Problem

mdBook does not support converting [Toc] syntax in Markdown files to article summaries

### Proposed Solution

Hope to support the [toc] or [TOC] syntax in Markdown files, it can convert all the symbols waiting for # in the article into the table of contents of the article

![Snipaste_2023-06-15_13-41-44](https://github.com/rust-lang/mdBook/assets/39946319/974de871-53c7-4b04-9cba-f270c4efef48)
![Snipaste_2023-06-15_13-42-00](https://github.com/rust-lang/mdBook/assets/39946319/8b1012e0-2334-492d-b9d0-60d01f244ba2)

**Comment by ehuss** [comment] 2023-06-15 13:04
Thanks for the report, closing as a duplicate of #153.

**Closed by ehuss** 2023-06-15 13:04 UTC
Labels: C-enhancement
