### ISSUE TITLE
Bug: relative links to 'README.md' files don't resolve

### ISSUE THREAD

**Issue by chrstnst** [rust-lang/mdBook#1920] opened 2022-11-08 05:45 UTC
Linking to other markdown files in the book's source generally works as expected. The exception are links to 'README.md' files. Clicking on such links in the HTML version of the book results in a 404 (Document not found) error.

Steps to reproduce:

1. Create a book's source as follows:

    `src/book.toml`:
    ```toml
    [book]
    authors = []
    language = "en"
    multilingual = false
    src = "src"
    ```

    `src/SUMMARY.md`:
    ```markdown
    # Summary

    - [Chapter 1](./chapter_1/README.md)
    - [Chapter 2](./chapter_2/README.md)
        - [Chapter 2.1](./chapter_2/chapter_2.1.md)
    ```

    `src/chapter_1/README.md`:
    ```markdown
    # Chapter 1

    - Link to [Chapter 2](../chapter_2/README.md)
    - Link to [Chapter 2.1](../chapter_2/chapter_2.1.md)
    ```

    `src/chapter_2/README.md`:
    ```markdown
    # Chapter 2
    ```

    `src/chapter_2/chapter_2.1.md`:
    ```markdown
    # Chapter 2.1
    ```

2. Build and serve the book: `mdbook serve`

3. Open the book in your browser: `http://localhost:3000`

4. Click on the links in Chapter 1: while the link to Chapter 2.1 works fine, the link to Chapter 2 doesn't.

**Comment by chrstnst** [comment] 2022-11-08 05:51
I have already investigated the reason for this error. Please also see my accompanying PR (#1921) for a suggested fix.

README.md files get a special treatment in mdbook. They are renamed to index.md. This behavior is described [here](https://rust-lang.github.io/mdBook/format/markdown.html#links) in mdbook's manual.

While the files are renamed, the destination of relative links to these files in the source of the book are not changed accordingly.

**Comment by ehuss** [comment] 2022-11-08 13:48
Thanks for the report! I think this is a duplicate of #984, so closing in favor of that.

**Closed by ehuss** 2022-11-08 13:48 UTC

**Comment by chrstnst** [comment] 2022-11-12 06:54
@ehuss Sorry, for opening a duplicate issue. But I also provided a possible [fix](https://github.com/rust-lang/mdBook/pull/1921). Any chance of merging it?
