### ISSUE TITLE
Copy command in "The book" copies the $ character too

### ISSUE THREAD

**Issue by deepdmistry** [rust-lang/mdBook#1369] opened 2020-10-28 15:34 UTC
Minor inconvenience, while going through the first chapter of [the book, ](https://doc.rust-lang.org/book/ch01-01-installation.html) the copy button copies the `$` sign too, causing terminal error.

**Comment by ehuss** [comment] 2020-10-28 17:56
Thanks for the report!  This is a duplicate of #864, so closing in favor of that.

**Closed by ehuss** 2020-10-28 17:56 UTC
